export const LIST_PROFILE = 'LIST_PROFILE';
export const ADD_PROFILE = 'ADD_PROFILE';
export const GET_PROFILE = 'GET_PROFILE';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const DELETE_PROFILE = 'DELETE_PROFILE';